name: Python tests (Lab 5 Reliability)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest -v -s | tee lab_5.log

        # Сборка артефакта проекта
      - name: Create build artifact
        run: |
          mkdir -p build
          cp -r lab_5.py test_lab5_reliability.py lab5.log build/
          tar -czf build-artifact.tar.gz build

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: jelinski-moranda-build
          path: build-artifact.tar.gz
